language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
branches:
  only:
    - release
script:
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] || [ "$TRAVIS_BRANCH" == "release" ]; then yarn appr; fi'
  