language: node_js
node_js:
  - "12"
cache:
  directories:
    - node_modules
branches:
  only:
    - release
script:
  - 'export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)'
  - 'echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH"'
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ] && [ "$BRANCH" == "release" ]; then npm run appr; fi'
  